# Generated by Django 4.2.20 on 2025-04-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_meetingnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assignee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('낮음', '낮음'), ('중간', '중간'), ('높음', '높음')], default='중간', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('계획 중', '계획 중'), ('진행 중', '진행 중'), ('완료', '완료')], default='계획 중', max_length=20),
        ),
    ]
