# Generated by Django 4.2.20 on 2025-04-25 03:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_project_assignee_project_end_date_project_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingnote',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, default='2024-12-31', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('낮음', '낮음'), ('중간', '중간'), ('높음', '높음')], default='중간', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, default='2024-01-01', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('계획 중', '계획 중'), ('진행 중', '진행 중'), ('완료', '완료')], default='계획 중', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
